name: ChatGPT Cleaner

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install --with-deps chromium

      - name: Restore sessions
        run: |
          mkdir -p sessions

          echo "${{ secrets.CSE_SESSION_ZIP }}" | base64 -d > cse.zip
          unzip -o cse.zip -d sessions

          echo "${{ secrets.UW_SESSION_ZIP }}" | base64 -d > uw.zip
          unzip -o uw.zip -d sessions

          echo "${{ secrets.F23_SESSION_ZIP }}" | base64 -d > f23.zip
          unzip -o f23.zip -d sessions
          # Add as necessary for other accounts

      - name: Run cleaner
        run: |
          python cleaner.py